---
title: Mouse Colony Summary
author: 
 - name: Shuai Yuan
 url: https://www.straublab.pitt.edu/lab/
 affiliation: University of Pittsburgh
 email: yuans@pitt.edu
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: 
 html_document:
 toc: true
 toc_float: true
 toc_depth: 5
 number_sections: true
 self_contained: yes
 theme: flatly
---

```{r setup, include=FALSE}
library(ragg)
# library(Cairo)

# ragg_png = function(...) {
# ragg::agg_png(..., res = 300, units = "in")
# }

options(
 htmltools.dir.version = FALSE, 
 knitr.duplicate.label = "allow", 
 DT.options = list(scrollX = TRUE), 
 scipen = 999
 # bitmapType = "cairo"
 )
knitr::opts_chunk$set(
 # dev = "CairoPNG",
 # units = "in",
 dev = "agg_png",
 fig.ext = "png",
 dev.args=list(res = 300, units = "in"),
 dpi = 100,
 out.width = "100%",
 cache = FALSE,
 echo = FALSE,
 message = FALSE, 
 warning = FALSE,
 hiline = TRUE
 )
```

```{r}
library(tidyverse)
library(ggped)
library(openxlsx)
library(glue)
library(ggtext)
library(plotly)
library(patchwork)

invisible(
  list.files("helper_functions/", pattern = "\\.R$", full.names = TRUE, recursive = TRUE) %>% map(source)
)
```

```{r}
dfColonyNew <- read.xlsx("data/SoftMouse.NET-Mouse List-MeganMiller2026-04-06 1446.xlsx", detectDates = TRUE) %>%
  mutate(
    Genotype = str_to_title(Genotype), 
    Date.of.Birth = as.Date(Date.of.Birth, "%m-%d-%Y"), 
    End.Date = as.Date(End.Date, "%m-%d-%Y")
    ) %>%
  select(Physical.Tag, Sex, Date.of.Birth, End.Date, End.Type, Age, State, Genotype, Mouseline, Generation, Sire.Tag, Dam.Tag, "Mating.Partner's.Tag")

dfColonyOld <- read.xlsx("data/CYB5R4_Colony_20260227.xlsx", detectDates = TRUE) %>%
  mutate(
    Genotype = str_to_title(Genotype), 
    Date.of.Birth = as.Date(Date.of.Birth, "%m-%d-%Y")
    ) %>%
  select(Physical.Tag, Sex, Date.of.Birth, End.Date, End.Type, Age, State, Genotype, Mouseline, Generation, Sire.Tag, Dam.Tag, "Mating.Partner's.Tag")

dfColony <- rbind(dfColonyNew, dfColonyOld %>% filter(!Physical.Tag %in% dfColonyNew$Physical.Tag))

# dfColony <- dfColonyOld %>%
#   left_join(dfColonyNew %>% select(Physical.Tag, End.Date, End.Type), by = "Physical.Tag")

vtGeno <- dfColony %>%
  pull(Genotype) %>%
  map(function(x) str_split_1(x, ", ")) %>%
  unlist() %>%
  str_replace("\\(.*\\)", "") %>%
  unique()

dfColony <- reduce(vtGeno, function(df, x) df %>% mutate(!!x := str_extract(Genotype, glue("(?<={x}\\().*?(?=\\))"))), .init = dfColony)

dfColony <- reduce(vtGeno, function(df, x) df %>% mutate(!!x := map_chr(df[[x]], function(x) strsplit(x, "/") %>% unlist() %>% sort() %>% paste0(collapse = "/"))), .init = dfColony)

dfColony <- reduce(vtGeno, function(df, x) df %>% mutate(!!x := map_chr(df[[x]], function(x) ifelse(x == "", "NA", x))), .init = dfColony)

dfColony <- dfColony %>%
  mutate(
    Age.Wk = map2_chr(Date.of.Birth, End.Date, function(x, y) {
      if (is.na(y)) {
        formatC(as.numeric(today() - x)/7, format = "f", digits = 1) %>% paste("wk")
      } else {
        formatC(as.numeric(y - x)/7, format = "f", digits = 1) %>% paste("wk")
      }
      })
  )

# dfColony <- dfColony %>%
#   mutate(
#     Age.Wk = map2_chr(Date.of.Birth, End.Date, function(x, y) {
#       if (is.na(y)) {
#         formatC(as.numeric(today() - x)/7, format = "f", digits = 1) %>% paste("wk")
#       } else {
#         formatC(as.numeric(y - x)/7, format = "f", digits = 1) %>% paste("wk")
#       }
#       })
#   )

write.xlsx(dfColony, glue('data/CYB5R4_Colony_{format(Sys.Date(), "%Y%m%d")}.xlsx'))
```


# CYB5R4 KO Colony

```{r}
dfKo <- subset_descendants(dfColony, "CYB5R4 F1 #15")

peds <- with(dfKo,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.KO = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "Ko") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, Generation, sep = "\n")
    ) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.KO"), 
    # features.as.lables = c("Cyb5r4"),
    # col.lables = c("Wt/Wt" = "black", "Ko/Ko" = "red", "Ko/Wt" = "pink", "Fl/Fl" = "steelblue", "Fl/Wt" = "lightblue", "?/?" = "grey", "+/?" = "green", "+/+" = "green", "-/-" = "black", "NA" = "black")
    plot.kinship.label = FALSE, 
    text.size = 4
    ) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("red"), main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave(glue('{format(Sys.Date(), "%Y%m%d")}_CYB5R4KO_Colony.pdf'), width = 35, height = 20, dpi = 600)
```

# CYB5R4FL,Cdh5-Cre Colony

```{r}
dfFl <- subset_descendants(dfColony, "CYB5R4 F1 #14")

dfCmvCre <- bind_rows(
  subset_descendants(dfColony, "JAX006054-1", include.breeder = FALSE), 
  subset_descendants(dfColony, "JAX006054-2", include.breeder = FALSE)) %>%
  distinct()

dfLysMCre <- subset_descendants(dfColony, "JAX004781-2", include.breeder = FALSE)

dfInsCre <- subset_descendants(dfColony, "1898", include.breeder = FALSE)

dfFlCdh5Cre <- dfFl %>%
  filter(!Physical.Tag %in% c(dfCmvCre$Physical.Tag, dfLysMCre$Physical.Tag, dfInsCre$Physical.Tag)) %>%
  bind_rows(dfColony %>% filter(Physical.Tag %in% c("27410", "27337")))

peds <- with(dfFlCdh5Cre,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.Fl = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "Fl") * 0.5
         }), 
         `Cdh5-CreErt2` = map_dbl(Icdh5cre, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "+") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, Icdh5cre, Generation, sep = "\n")) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.Fl", "Cdh5-CreErt2"), 
    # features.as.lables = c("Cyb5r4", "Icdh5cre"),
    # col.lables = c("Wt/Wt" = "black", "Ko/Ko" = "red", "Ko/Wt" = "pink", "Fl/Fl" = "steelblue", "Fl/Wt" = "lightblue", "?/?" = "grey", "?/+" = "green", "+/+" = "green", "+" = "green", "-/+" = "black", "-/-" = "black", "NA" = "black"),
    plot.kinship.label = FALSE, 
    show.legend = TRUE, 
    text.size = 6) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("steelblue", "violet"), main.feature.black = FALSE) +
  # scale_feature.name(set = "Set2", main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave(glue('{format(Sys.Date(), "%Y%m%d")}_CYB5R4FL.Cdh5-Cre_Colony.pdf'), width = 70, height = 20, dpi = 600, limitsize = FALSE)
```

# CYB5R4FL,CMV-Cre Colony

```{r}
dfFl <- subset_descendants(dfColony, "CYB5R4 F1 #14")

dfCdh5Cre <- subset_descendants(dfColony, "18609", include.breeder = FALSE)

dfLysMCre <- subset_descendants(dfColony, "JAX004781-2", include.breeder = FALSE)

dfInsCre <- subset_descendants(dfColony, "1898", include.breeder = FALSE)

dfFlCmvCre <- dfFl %>%
  filter(!Physical.Tag %in% c(dfCdh5Cre$Physical.Tag, dfLysMCre$Physical.Tag, dfInsCre$Physical.Tag))

peds <- with(dfFlCmvCre,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.Fl = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x %in% c("Fl", "Ko")) * 0.5
         }), 
         Cmv.Cre = map_dbl(`Cmv-Cre`, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "+") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, `Cmv-Cre`, Generation, sep = "\n")) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.Fl", "Cmv.Cre"), 
    plot.kinship.label = FALSE, 
    show.legend = TRUE, 
    text.size = 6) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("steelblue", "violet"), main.feature.black = FALSE) +
  # scale_feature.name(set = "Set2", main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave(glue('{format(Sys.Date(), "%Y%m%d")}_CYB5R4FL.Cmv-Cre_Colony.pdf'), width = 30, height = 20, dpi = 600)
```


# CYB5R4FL,LysM-Cre Colony

```{r}
dfFl <- subset_descendants(dfColony, "CYB5R4 F1 #14")

dfCdh5Cre <- subset_descendants(dfColony, "18609", include.breeder = FALSE)

dfCmvCre <- bind_rows(
  subset_descendants(dfColony, "JAX006054-1", include.breeder = FALSE), 
  subset_descendants(dfColony, "JAX006054-2", include.breeder = FALSE)) %>%
  distinct()

dfInsCre <- subset_descendants(dfColony, "1898", include.breeder = FALSE)

dfFlLysMCre <- dfFl %>%
  filter(!Physical.Tag %in% c(dfCdh5Cre$Physical.Tag, dfCmvCre$Physical.Tag, dfInsCre$Physical.Tag))

peds <- with(dfFlLysMCre,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.Fl = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x %in% c("Fl", "Ko")) * 0.5
         }), 
         `LysM.Cre` = map_dbl(`Lysm-Cre`, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "+") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, `Lysm-Cre`, Generation, sep = "\n")) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.Fl", "LysM.Cre"), 
    plot.kinship.label = FALSE, 
    show.legend = TRUE, 
    text.size = 6) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("steelblue", "violet"), main.feature.black = FALSE) +
  # scale_feature.name(set = "Set2", main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave(glue('{format(Sys.Date(), "%Y%m%d")}_CYB5R4FL.LysM-Cre_Colony.pdf'), width = 50, height = 20, dpi = 600, limitsize = FALSE)
```

# CYB5R4FL,Ins-Cre Colony


```{r}
dam_ids <- c("1292", "1300", "1453")
dfFlInsCre <- map_dfr(dam_ids, function(x){
  # ids <- find_ancestors_and_offspring(x, dfColony)
  ids <- trace_descendants_plus_ancestors_and_sibs(x, dfColony)
  dfColony %>%
    filter(Physical.Tag %in% ids)
}) %>%
  distinct() %>%
  bind_rows(dfColony %>% filter(Physical.Tag == "1898"))
  # bind_rows(dfColony %>% filter(grepl("JAX", Physical.Tag))) %>%
  # distinct()

peds <- with(dfFlInsCre,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.Fl = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x %in% c("Fl", "Ko")) * 0.5
         }), 
         `Ins1.Cre` = map_dbl(`Ins1cre`, function(x) {
           if(is.na(x)) return(0)
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "+") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, `Ins1cre`, Generation, sep = "\n")) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.Fl", "Ins1.Cre"), 
    plot.kinship.label = FALSE, 
    show.legend = TRUE, 
    text.size = 6) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("steelblue", "violet"), main.feature.black = FALSE) +
  # scale_feature.name(set = "Set2", main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave(glue('{format(Sys.Date(), "%Y%m%d")}_CYB5R4FL.Ins1Cre_Colony.pdf'), width = 50, height = 20, dpi = 600, limitsize = FALSE)
```

# Extract a subset and plot

```{r fig.width=6, fig.height=12}
pup_ids <- c("3347", "3371", "3389", "3391", "3392", "3393", "3394", "3395", "3396")

subset_ids <- map(pup_ids, ~get_ancestors(dfColony, .x, include_self = TRUE)) %>%
  unlist() %>%
  unique()

df_colony_sub <- dfColony %>%
  filter(Physical.Tag %in% subset_ids)

peds <- with(df_colony_sub,
             pedigree(
               id = Physical.Tag, 
               dadid = Sire.Tag, 
               momid = Dam.Tag, 
               sex = Sex, 
               status = ifelse(State == "Ended" | is.na(State), 1, 0)
             ))

dfPeds <- dfalign.pedigree(peds) %>%
  left_join(dfColony, by = join_by(Name == Physical.Tag)) %>%
  mutate(Cyb5r4.Fl = map_dbl(Cyb5r4, function(x) {
           x <- strsplit(x, "/") %>% unlist()
           sum(x %in% c("Fl", "Ko")) * 0.5
         }), 
         `Lyz2Cre` = map_dbl(`Lysm-Cre`, function(x) {
           if(is.na(x)) return(0)
           x <- strsplit(x, "/") %>% unlist()
           sum(x == "+") * 0.5
         }))
  
dfPeds %>%
  mutate(
    Name = paste(Name, Age.Wk, Cyb5r4, `Lyz2Cre`, Generation, sep = "\n")) %>%
  ggdraw.pedigree1(
    features = c("Cyb5r4.Fl", "Lyz2Cre"), 
    plot.kinship.label = FALSE, 
    show.legend = TRUE, 
    text.size = 6) +
  coord_cartesian(clip = "off") +
  scale_feature.name_manual(values = c("steelblue", "violet"), main.feature.black = FALSE) +
  # scale_feature.name(set = "Set2", main.feature.black = FALSE) +
  theme(
    plot.margin = margin(0, 10, 50, 0)
  )

ggsave("selected_mice_tree.jpg", width = 6, height = 12, dpi = 300, limitsize = FALSE)
```


# Mice ready to use

```{r}
dfColony <- read.xlsx("data/CYB5R4_Colony_20260406.xlsx", detectDates = TRUE) %>%
  mutate(
    Age.Wk = map2_chr(Date.of.Birth, End.Date, function(x, y) {
      if (is.na(y)) {
        formatC(as.numeric(today() - x)/7, format = "f", digits = 1) %>% paste("wk")
      } else {
        formatC(as.numeric(y - x)/7, format = "f", digits = 1) %>% paste("wk")
      }
      }), 
    Age.Wks = map2_chr(Date.of.Birth, End.Date, function(x, y) {
      if (is.na(y)) {
        formatC(as.numeric(today() - x)/7, format = "f", digits = 1)
      } else {
        formatC(as.numeric(y - x)/7, format = "f", digits = 1)
      }
      })
  ) 

dfColony <- dfColony %>%
  filter(State != "Ended") %>%
  filter(grepl("Wt/Wt|Ko/Ko|Fl/Fl|Ko/Wt|Fl/Wt", Cyb5r4)) %>%
  select(Physical.Tag, Sex, Date.of.Birth, Age.Wks, Genotype, State)

df_softmouse <- read.xlsx("data/SoftMouse.NET-Mouse List-MeganMiller2026-04-06 1446.xlsx") %>%
  select(Physical.Tag, Comment)

dfColony <- dfColony %>%
  left_join(df_softmouse, by = "Physical.Tag")

write.csv(dfColony, "Mice ready to use.csv", row.names = FALSE)
```


